/**
 * Tree-sitter-specific adaptations when transpiling beskid.pest.
 * Edit conflicts here if `tree-sitter generate` reports new ones.
 */

/** Pest rule names omitted from generated grammar (handled manually or lexer-only). */
export const SKIP_RULES = new Set([
  'WHITESPACE',
  'NEWLINE',
  'DocGap',
  'ASCII_ALPHA_UNDERSCORE',
  'ASCII_ALPHA',
  'ASCII_ALPHANUMERIC',
  'ASCII_DIGIT',
  'Keyword',
  'TypeDeclarationKeyword',
  'EnumDeclarationKeyword',
  'ContractDeclarationKeyword',
  'AttributeDeclarationKeyword',
  'ImplKeyword',
  'ExtendKeyword',
  'MatchKeyword',
  'EventKeyword',
  'WhenKeyword',
  'IfKeyword',
  'ElseKeyword',
  'WhileKeyword',
  'ForKeyword',
  'InKeyword',
  'ReturnKeyword',
  'BreakKeyword',
  'ContinueKeyword',
  'LetKeyword',
  'MutKeyword',
  'ModKeyword',
  'UseKeyword',
  'PubKeyword',
  'RefKeyword',
  'OutKeyword',
  'TestKeyword',
  'SkipKeyword',
  'SpawnKeyword',
  'AsyncKeyword',
  'AwaitKeyword',
  'HostKeyword',
  'RegistryKeyword',
  'ScopeKeyword',
  'StartupKeyword',
  'InitKeyword',
  'DisposeKeyword',
  'WithKeyword',
  'LaunchKeyword',
  'InjectKeyword',
  'SingleKeyword',
  'TransientKeyword',
  'GlobalKeyword',
  'ParentKeyword',
  'FourSlashLineComment',
  'OrdinaryLineComment',
  'DocLineContent',
  'StringContent',
  'InterpolationExpression',
  'StringText',
  'ItemList',
  'InnerItem',
  'InlineModuleBody',
  'HostBodyItem',
  'ScopeBodyItem',
  'TestBodyItem',
  'PostfixOperator',
  'CallOperator',
  'MemberAccess',
  'CallExpression',
  'MacroInvocationBlock',
  'BlockExpression',
  'AssignmentOperator',
  'MatchGuard',
  'TypeAnnotation',
  'BeskidTypeList',
  'Program',
  'ItemWithDocs',
  'ImplMethodWithDocs',
  'ParameterWithDocs',
  'FieldWithDocs',
  'EnumVariantWithDocs',
  'ContractItemWithDocs',
  'TestBodyItemWithDocs',
  'DocRun',
]);

/** Pest name → tree-sitter rule name. */
export const RENAME_RULES = {
  Program: 'source_file',
  ItemWithDocs: 'item_with_docs',
  InnerItem: '_item',
  Statement: '_statement',
  Expression: '_expression',
  BeskidType: '_type',
  Pattern: '_pattern',
  Field: '_field',
  BlockExpression: 'block',
  Path: 'type_path',
  TypeName: '_type_name',
};

/** Rules emitted from hand-written templates instead of transpiler. */
export const MANUAL_RULES = new Set([
  'source_file',
  'item_with_docs',
  '_item',
  'doc_comment',
  'line_comment',
  'block_comment',
  'identifier',
  '_type',
  '_type_name',
  'type_path',
  '_type_path',
  '_type_path_segment',
  '_expression',
  '_statement',
  '_pattern',
  '_field',
  'assignment_expression',
  'logical_or_expression',
  'logical_and_expression',
  'equality_expression',
  'comparison_expression',
  'additive_expression',
  'multiplication_expression',
  'unary_expression',
  'spawn_expression',
  'postfix_expression',
  'primary_expression',
  'lambda_expression',
  '_lambda_parameters',
  'lambda_body',
  'struct_literal_expression',
  '_enum_constructor_expression',
  'wildcard_pattern',
]);

/** GLR conflict sets (tree-sitter `conflicts` field). */
export const CONFLICTS = [
  ['_type', '_expression'],
  ['_expression', '_pattern'],
  ['_type_path_segment'],
  ['arrow_function_type', '_lambda_parameters'],
  ['type_reference', 'parameter_modifier'],
  ['contract_method_signature', 'contract_embedding'],
  ['registry_block', 'registry_entry'],
  ['_type_path_segment', 'contract_embedding'],
  ['_type_path_segment', 'primary_expression'],
  ['_type_path_segment', '_lambda_parameters'],
  ['_type_path_segment', '_parameter'],
  ['_enum_constructor_expression'],
  ['_type_path_segment', 'lambda_parameter'],
  ['_type_path_segment', 'lambda_parameter', 'primary_expression'],
  ['macro_invocation'],
  ['lambda_parameter', 'primary_expression'],
  ['lambda_body', 'primary_expression'],
  ['_lambda_parameters', 'primary_expression'],
];
